"""Helpers for Rust-backed Valdi polyglot modules."""

load("@bazel_skylib//lib:paths.bzl", "paths")
load("@bazel_skylib//rules:write_file.bzl", "write_file")
load("@rules_rust//rust:defs.bzl", "rust_static_library")

_VALDI_RUST_SUPPORT_RS = """// Generated by valdi_rust_native_module.
// Shared Rust ABI support for Valdi generated native bridges.

use std::ffi::{c_char, c_void};
use std::marker::PhantomData;
use std::sync::Mutex;

pub type Double = f64;
pub type Bool = bool;
pub type Long = i64;
pub type Bytes = Vec<u8>;

#[repr(C)]
#[derive(Clone, Copy)]
pub struct ValdiRustStringView {
    pub data: *const c_char,
    pub len: usize,
}

impl ValdiRustStringView {
    pub fn from_str(value: &str) -> Self {
        Self {
            data: value.as_ptr() as *const c_char,
            len: value.len(),
        }
    }

    pub fn to_string(self) -> String {
        if self.data.is_null() {
            return String::new();
        }

        let bytes = unsafe { std::slice::from_raw_parts(self.data as *const u8, self.len) };
        std::str::from_utf8(bytes)
            .expect("Valdi Rust string view is not valid UTF-8")
            .to_string()
    }
}

#[repr(C)]
pub struct ValdiRustOwnedString {
    pub data: *const c_char,
    pub len: usize,
    pub free: unsafe extern "C" fn(*const c_char, usize),
}

unsafe extern "C" fn valdi_rust_free_owned_string(data: *const c_char, len: usize) {
    if data.is_null() {
        return;
    }

    let slice = std::ptr::slice_from_raw_parts_mut(data as *mut u8, len);
    unsafe {
        drop(Box::from_raw(slice));
    }
}

impl ValdiRustOwnedString {
    pub fn from_value<T: Into<String>>(value: T) -> Self {
        let mut bytes = value.into().into_bytes().into_boxed_slice();
        let len = bytes.len();
        let data = bytes.as_mut_ptr() as *const c_char;
        std::mem::forget(bytes);

        Self {
            data,
            len,
            free: valdi_rust_free_owned_string,
        }
    }

    pub fn into_string(self) -> String {
        let bytes = if self.data.is_null() {
            Vec::new()
        } else {
            unsafe { std::slice::from_raw_parts(self.data as *const u8, self.len).to_vec() }
        };
        unsafe {
            (self.free)(self.data, self.len);
        }
        String::from_utf8(bytes).expect("Valdi Rust owned string is not valid UTF-8")
    }
}

#[repr(C)]
#[derive(Clone, Copy)]
pub struct ValdiRustBytesView {
    pub data: *const u8,
    pub len: usize,
}

impl ValdiRustBytesView {
    pub fn from_slice(value: &[u8]) -> Self {
        Self {
            data: value.as_ptr(),
            len: value.len(),
        }
    }

    pub fn to_vec(self) -> Bytes {
        if self.data.is_null() {
            return Vec::new();
        }

        unsafe { std::slice::from_raw_parts(self.data, self.len).to_vec() }
    }
}

#[repr(C)]
pub struct ValdiRustOwnedBytes {
    pub data: *const u8,
    pub len: usize,
    pub free: unsafe extern "C" fn(*const u8, usize),
}

unsafe extern "C" fn valdi_rust_free_owned_bytes(data: *const u8, len: usize) {
    if data.is_null() {
        return;
    }

    let slice = std::ptr::slice_from_raw_parts_mut(data as *mut u8, len);
    unsafe {
        drop(Box::from_raw(slice));
    }
}

impl ValdiRustOwnedBytes {
    pub fn from_value<T: Into<Bytes>>(value: T) -> Self {
        let mut bytes = value.into().into_boxed_slice();
        let len = bytes.len();
        let data = bytes.as_mut_ptr() as *const u8;
        std::mem::forget(bytes);

        Self {
            data,
            len,
            free: valdi_rust_free_owned_bytes,
        }
    }

    pub fn into_vec(self) -> Bytes {
        let bytes = if self.data.is_null() {
            Vec::new()
        } else {
            unsafe { std::slice::from_raw_parts(self.data, self.len).to_vec() }
        };
        unsafe {
            (self.free)(self.data, self.len);
        }
        bytes
    }
}

#[repr(C)]
#[derive(Clone, Copy)]
pub struct ValdiRustHandle {
    pub ptr: *mut c_void,
    pub retain: unsafe extern "C" fn(*mut c_void),
    pub release: unsafe extern "C" fn(*mut c_void),
}

#[repr(transparent)]
pub struct ValdiRustTypedHandle<T> {
    handle: ValdiRustHandle,
    marker: PhantomData<T>,
}

unsafe impl<T> Send for ValdiRustTypedHandle<T> {}

impl<T> Clone for ValdiRustTypedHandle<T> {
    fn clone(&self) -> Self {
        Self {
            handle: self.handle,
            marker: PhantomData,
        }
    }
}

impl<T> Copy for ValdiRustTypedHandle<T> {}

impl<T> ValdiRustTypedHandle<T> {
    pub fn from_handle(handle: ValdiRustHandle) -> Self {
        Self {
            handle,
            marker: PhantomData,
        }
    }

    pub fn into_handle(self) -> ValdiRustHandle {
        self.handle
    }

    pub fn into_return_handle(self) -> ValdiRustHandle {
        self.retain();
        self.handle
    }

    pub fn as_handle(&self) -> ValdiRustHandle {
        self.handle
    }

    pub fn retain_for_storage(&self) -> ValdiRustRetainedHandle<T> {
        self.retain();
        ValdiRustRetainedHandle {
            handle: self.handle,
            marker: PhantomData,
        }
    }

    pub fn retain(&self) {
        unsafe {
            (self.handle.retain)(self.handle.ptr);
        }
    }

    pub unsafe fn release(&self) {
        unsafe {
            (self.handle.release)(self.handle.ptr);
        }
    }
}

pub struct ValdiRustRetainedHandle<T> {
    handle: ValdiRustHandle,
    marker: PhantomData<T>,
}

unsafe impl<T> Send for ValdiRustRetainedHandle<T> {}

impl<T> Clone for ValdiRustRetainedHandle<T> {
    fn clone(&self) -> Self {
        unsafe {
            (self.handle.retain)(self.handle.ptr);
        }
        Self {
            handle: self.handle,
            marker: PhantomData,
        }
    }
}

impl<T> Drop for ValdiRustRetainedHandle<T> {
    fn drop(&mut self) {
        unsafe {
            (self.handle.release)(self.handle.ptr);
        }
    }
}

impl<T> ValdiRustRetainedHandle<T> {
    pub fn as_typed_handle(&self) -> ValdiRustTypedHandle<T> {
        ValdiRustTypedHandle::from_handle(self.handle)
    }

    pub fn as_handle(&self) -> ValdiRustHandle {
        self.handle
    }
}

pub enum ValdiRustAnyMarker {}
pub enum ValdiRustArrayMarker<T> {
    _Phantom(PhantomData<T>),
}
pub enum ValdiRustMapMarker<K, V> {
    _Phantom(PhantomData<(K, V)>),
}
pub enum ValdiRustOptionalMarker<T> {
    _Phantom(PhantomData<T>),
}
pub enum ValdiRustPromiseMarker<T> {
    _Phantom(PhantomData<T>),
}
pub enum ValdiRustFunctionMarker {}

pub type Any = ValdiRustTypedHandle<ValdiRustAnyMarker>;
pub type Array<T> = ValdiRustTypedHandle<ValdiRustArrayMarker<T>>;
pub type Map<K, V> = ValdiRustTypedHandle<ValdiRustMapMarker<K, V>>;
pub type Optional<T> = ValdiRustTypedHandle<ValdiRustOptionalMarker<T>>;
pub type Function = ValdiRustTypedHandle<ValdiRustFunctionMarker>;

#[repr(C)]
#[derive(Clone, Copy)]
pub struct ValdiRustPromiseResolver {
    pub context: *mut c_void,
    pub retain: unsafe extern "C" fn(*mut c_void),
    pub release: unsafe extern "C" fn(*mut c_void),
    pub resolve_double: extern "C" fn(*mut c_void, f64),
    pub resolve_bool: extern "C" fn(*mut c_void, bool),
    pub resolve_long: extern "C" fn(*mut c_void, i64),
    pub resolve_string: extern "C" fn(*mut c_void, ValdiRustStringView),
    pub resolve_bytes: extern "C" fn(*mut c_void, ValdiRustBytesView),
    pub resolve_handle: extern "C" fn(*mut c_void, ValdiRustHandle),
    pub resolve_void: extern "C" fn(*mut c_void),
    pub reject: extern "C" fn(*mut c_void, ValdiRustStringView),
}

#[repr(C)]
pub struct ValdiRustPromise {
    pub context: *mut c_void,
    pub run: unsafe extern "C" fn(*mut c_void, ValdiRustPromiseResolver),
    pub release: unsafe extern "C" fn(*mut c_void),
}

pub trait ValdiRustPromiseValue: Send + 'static {
    fn resolve_with(resolver: &ValdiRustPromiseResolver, value: Self);
}

impl ValdiRustPromiseValue for Double {
    fn resolve_with(resolver: &ValdiRustPromiseResolver, value: Self) {
        (resolver.resolve_double)(resolver.context, value);
    }
}

impl ValdiRustPromiseValue for Bool {
    fn resolve_with(resolver: &ValdiRustPromiseResolver, value: Self) {
        (resolver.resolve_bool)(resolver.context, value);
    }
}

impl ValdiRustPromiseValue for Long {
    fn resolve_with(resolver: &ValdiRustPromiseResolver, value: Self) {
        (resolver.resolve_long)(resolver.context, value);
    }
}

impl ValdiRustPromiseValue for String {
    fn resolve_with(resolver: &ValdiRustPromiseResolver, value: Self) {
        let view = ValdiRustStringView::from_str(&value);
        (resolver.resolve_string)(resolver.context, view);
    }
}

impl ValdiRustPromiseValue for Bytes {
    fn resolve_with(resolver: &ValdiRustPromiseResolver, value: Self) {
        let view = ValdiRustBytesView::from_slice(&value);
        (resolver.resolve_bytes)(resolver.context, view);
    }
}

impl<T: Send + 'static> ValdiRustPromiseValue for ValdiRustTypedHandle<T> {
    fn resolve_with(resolver: &ValdiRustPromiseResolver, value: Self) {
        (resolver.resolve_handle)(resolver.context, value.into_return_handle());
    }
}

impl<T: Send + 'static> ValdiRustPromiseValue for ValdiRustRetainedHandle<T> {
    fn resolve_with(resolver: &ValdiRustPromiseResolver, value: Self) {
        (resolver.resolve_handle)(resolver.context, value.as_typed_handle().into_return_handle());
    }
}

impl ValdiRustPromiseValue for () {
    fn resolve_with(resolver: &ValdiRustPromiseResolver, _value: Self) {
        (resolver.resolve_void)(resolver.context);
    }
}

pub struct PromiseResolver<T> {
    resolver: ValdiRustPromiseResolver,
    marker: PhantomData<T>,
}

unsafe impl<T: Send + 'static> Send for PromiseResolver<T> {}

impl<T> Clone for PromiseResolver<T> {
    fn clone(&self) -> Self {
        unsafe {
            (self.resolver.retain)(self.resolver.context);
        }
        Self {
            resolver: self.resolver,
            marker: PhantomData,
        }
    }
}

impl<T> Drop for PromiseResolver<T> {
    fn drop(&mut self) {
        unsafe {
            (self.resolver.release)(self.resolver.context);
        }
    }
}

impl<T> PromiseResolver<T> {
    fn from_abi(resolver: ValdiRustPromiseResolver) -> Self {
        Self {
            resolver,
            marker: PhantomData,
        }
    }

    pub fn reject<S: AsRef<str>>(self, message: S) {
        let view = ValdiRustStringView::from_str(message.as_ref());
        (self.resolver.reject)(self.resolver.context, view);
    }
}

impl<T: ValdiRustPromiseValue> PromiseResolver<T> {
    pub fn resolve(self, value: T) {
        T::resolve_with(&self.resolver, value);
    }
}

enum ValdiRustPromiseInner<T> {
    Incoming(ValdiRustTypedHandle<ValdiRustPromiseMarker<T>>),
    Outgoing(Box<dyn FnOnce(PromiseResolver<T>) + Send + 'static>),
}

pub struct Promise<T> {
    inner: ValdiRustPromiseInner<T>,
}

impl<T: Send + 'static> Promise<T> {
    pub fn from_handle(handle: ValdiRustHandle) -> Self {
        Self {
            inner: ValdiRustPromiseInner::Incoming(ValdiRustTypedHandle::from_handle(handle)),
        }
    }

    pub fn as_handle(&self) -> Option<ValdiRustHandle> {
        match &self.inner {
            ValdiRustPromiseInner::Incoming(handle) => Some(handle.as_handle()),
            ValdiRustPromiseInner::Outgoing(_) => None,
        }
    }

    pub fn new<F>(executor: F) -> Self
    where
        F: FnOnce(PromiseResolver<T>) + Send + 'static,
    {
        Self {
            inner: ValdiRustPromiseInner::Outgoing(Box::new(executor)),
        }
    }

    pub fn rejected<S: Into<String> + Send + 'static>(message: S) -> Self {
        let message = message.into();
        Self::new(move |resolver| resolver.reject(message))
    }
}

impl<T: ValdiRustPromiseValue> Promise<T> {
    pub fn resolved(value: T) -> Self {
        Self::new(move |resolver| resolver.resolve(value))
    }

    pub fn into_ffi(self) -> ValdiRustPromise {
        match self.inner {
            ValdiRustPromiseInner::Incoming(_) => {
                Promise::<T>::rejected("Cannot return an incoming Valdi promise handle from Rust").into_ffi()
            }
            ValdiRustPromiseInner::Outgoing(executor) => {
                let state = ValdiRustPromiseState { executor: Some(executor) };
                ValdiRustPromise {
                    context: Box::into_raw(Box::new(state)) as *mut c_void,
                    run: valdi_rust_run_promise::<T>,
                    release: valdi_rust_release_promise::<T>,
                }
            }
        }
    }
}

struct ValdiRustPromiseState<T> {
    executor: Option<Box<dyn FnOnce(PromiseResolver<T>) + Send + 'static>>,
}

unsafe extern "C" fn valdi_rust_run_promise<T: ValdiRustPromiseValue>(
    ptr: *mut c_void,
    resolver: ValdiRustPromiseResolver,
) {
    if ptr.is_null() {
        let resolver = PromiseResolver::<T>::from_abi(resolver);
        resolver.reject("Rust promise executor is missing");
        return;
    }

    let mut state: Box<ValdiRustPromiseState<T>> =
        unsafe { Box::from_raw(ptr as *mut ValdiRustPromiseState<T>) };
    if let Some(executor) = state.executor.take() {
        executor(PromiseResolver::from_abi(resolver));
    } else {
        let resolver = PromiseResolver::<T>::from_abi(resolver);
        resolver.reject("Rust promise executor was already consumed");
    }
}

unsafe extern "C" fn valdi_rust_release_promise<T>(ptr: *mut c_void) {
    if ptr.is_null() {
        return;
    }

    unsafe {
        drop(Box::from_raw(ptr as *mut ValdiRustPromiseState<T>));
    }
}

#[repr(C)]
#[derive(Clone, Copy)]
pub struct ValdiRustDoubleObservableObserver {
    pub context: *mut c_void,
    pub next: extern "C" fn(*mut c_void, f64),
    pub complete: extern "C" fn(*mut c_void),
    pub release: extern "C" fn(*mut c_void),
}

unsafe impl Send for ValdiRustDoubleObservableObserver {}

impl ValdiRustDoubleObservableObserver {
    pub fn next(&self, value: f64) {
        (self.next)(self.context, value);
    }

    pub fn complete(&self) {
        (self.complete)(self.context);
    }

    pub fn release(&self) {
        (self.release)(self.context);
    }
}

pub type DoubleObservableObserver = ValdiRustDoubleObservableObserver;

#[repr(C)]
#[derive(Clone, Copy)]
pub struct ValdiRustBoolObservableObserver {
    pub context: *mut c_void,
    pub next: extern "C" fn(*mut c_void, bool),
    pub complete: extern "C" fn(*mut c_void),
    pub release: extern "C" fn(*mut c_void),
}

unsafe impl Send for ValdiRustBoolObservableObserver {}

impl ValdiRustBoolObservableObserver {
    pub fn next(&self, value: bool) {
        (self.next)(self.context, value);
    }

    pub fn complete(&self) {
        (self.complete)(self.context);
    }

    pub fn release(&self) {
        (self.release)(self.context);
    }
}

pub type BoolObservableObserver = ValdiRustBoolObservableObserver;

#[repr(C)]
#[derive(Clone, Copy)]
pub struct ValdiRustLongObservableObserver {
    pub context: *mut c_void,
    pub next: extern "C" fn(*mut c_void, i64),
    pub complete: extern "C" fn(*mut c_void),
    pub release: extern "C" fn(*mut c_void),
}

unsafe impl Send for ValdiRustLongObservableObserver {}

impl ValdiRustLongObservableObserver {
    pub fn next(&self, value: i64) {
        (self.next)(self.context, value);
    }

    pub fn complete(&self) {
        (self.complete)(self.context);
    }

    pub fn release(&self) {
        (self.release)(self.context);
    }
}

pub type LongObservableObserver = ValdiRustLongObservableObserver;

#[repr(C)]
#[derive(Clone, Copy)]
pub struct ValdiRustStringObservableObserver {
    pub context: *mut c_void,
    pub next: extern "C" fn(*mut c_void, ValdiRustStringView),
    pub complete: extern "C" fn(*mut c_void),
    pub release: extern "C" fn(*mut c_void),
}

unsafe impl Send for ValdiRustStringObservableObserver {}

impl ValdiRustStringObservableObserver {
    pub fn next(&self, value: ValdiRustStringView) {
        (self.next)(self.context, value);
    }

    pub fn complete(&self) {
        (self.complete)(self.context);
    }

    pub fn release(&self) {
        (self.release)(self.context);
    }
}

pub type StringObservableObserver = ValdiRustStringObservableObserver;

#[repr(C)]
#[derive(Clone, Copy)]
pub struct ValdiRustBytesObservableObserver {
    pub context: *mut c_void,
    pub next: extern "C" fn(*mut c_void, ValdiRustBytesView),
    pub complete: extern "C" fn(*mut c_void),
    pub release: extern "C" fn(*mut c_void),
}

unsafe impl Send for ValdiRustBytesObservableObserver {}

impl ValdiRustBytesObservableObserver {
    pub fn next(&self, value: ValdiRustBytesView) {
        (self.next)(self.context, value);
    }

    pub fn complete(&self) {
        (self.complete)(self.context);
    }

    pub fn release(&self) {
        (self.release)(self.context);
    }
}

pub type BytesObservableObserver = ValdiRustBytesObservableObserver;

#[repr(C)]
#[derive(Clone, Copy)]
pub struct ValdiRustHandleObservableObserver {
    pub context: *mut c_void,
    pub next: extern "C" fn(*mut c_void, ValdiRustHandle),
    pub complete: extern "C" fn(*mut c_void),
    pub release: extern "C" fn(*mut c_void),
}

unsafe impl Send for ValdiRustHandleObservableObserver {}

impl ValdiRustHandleObservableObserver {
    pub fn next(&self, value: ValdiRustHandle) {
        (self.next)(self.context, value);
    }

    pub fn complete(&self) {
        (self.complete)(self.context);
    }

    pub fn release(&self) {
        (self.release)(self.context);
    }
}

pub type HandleObservableObserver = ValdiRustHandleObservableObserver;

#[repr(C)]
pub struct ValdiRustObservableSubscription {
    pub ptr: *mut c_void,
    pub unsubscribe: unsafe extern "C" fn(*mut c_void),
}

pub type ObservableSubscription = ValdiRustObservableSubscription;

struct ValdiRustSubscriptionState<T> {
    value: T,
    unsubscribe: fn(T),
}

unsafe extern "C" fn valdi_rust_unsubscribe_state<T>(ptr: *mut c_void) {
    if ptr.is_null() {
        return;
    }

    let state: Box<ValdiRustSubscriptionState<T>> =
        unsafe { Box::from_raw(ptr as *mut ValdiRustSubscriptionState<T>) };
    (state.unsubscribe)(state.value);
}

unsafe extern "C" fn valdi_rust_noop_unsubscribe(_: *mut c_void) {}

impl ValdiRustObservableSubscription {
    pub fn from_state<T: Send + 'static>(value: T, unsubscribe: fn(T)) -> Self {
        let state = ValdiRustSubscriptionState { value, unsubscribe };
        Self {
            ptr: Box::into_raw(Box::new(state)) as *mut c_void,
            unsubscribe: valdi_rust_unsubscribe_state::<T>,
        }
    }

    pub fn empty() -> Self {
        Self {
            ptr: std::ptr::null_mut(),
            unsubscribe: valdi_rust_noop_unsubscribe,
        }
    }
}

pub trait ValdiRustObservable<Observer> {
    fn subscribe(self, observer: Observer) -> ValdiRustObservableSubscription;
}

pub fn subscribe<Source, Observer>(
    source: Source,
    observer: Observer,
) -> ValdiRustObservableSubscription
where
    Source: ValdiRustObservable<Observer>,
{
    source.subscribe(observer)
}

pub struct ValdiRustCallbackObservable<Observer> {
    subscribe: fn(Observer) -> ValdiRustObservableSubscription,
}

impl<Observer> ValdiRustCallbackObservable<Observer> {
    pub fn new(subscribe: fn(Observer) -> ValdiRustObservableSubscription) -> Self {
        Self { subscribe }
    }
}

impl<Observer> ValdiRustObservable<Observer> for ValdiRustCallbackObservable<Observer> {
    fn subscribe(self, observer: Observer) -> ValdiRustObservableSubscription {
        (self.subscribe)(observer)
    }
}

pub trait ValdiRustObserver<T>: Copy + Send + 'static {
    fn next(&self, value: T);
    fn release(&self);
}

pub trait ValdiRustObservableValue: Clone + Send + 'static {
    type Observer: ValdiRustObserver<Self>;
}

impl ValdiRustObservableValue for Double {
    type Observer = ValdiRustDoubleObservableObserver;
}

impl ValdiRustObservableValue for Bool {
    type Observer = ValdiRustBoolObservableObserver;
}

impl ValdiRustObservableValue for Long {
    type Observer = ValdiRustLongObservableObserver;
}

impl ValdiRustObservableValue for String {
    type Observer = ValdiRustStringObservableObserver;
}

impl ValdiRustObservableValue for Bytes {
    type Observer = ValdiRustBytesObservableObserver;
}

impl<T: Send + 'static> ValdiRustObservableValue for ValdiRustTypedHandle<T> {
    type Observer = ValdiRustHandleObservableObserver;
}

impl<T: Send + 'static> ValdiRustObservableValue for ValdiRustRetainedHandle<T> {
    type Observer = ValdiRustHandleObservableObserver;
}

impl ValdiRustObserver<f64> for ValdiRustDoubleObservableObserver {
    fn next(&self, value: f64) {
        ValdiRustDoubleObservableObserver::next(self, value);
    }

    fn release(&self) {
        ValdiRustDoubleObservableObserver::release(self);
    }
}

impl ValdiRustObserver<bool> for ValdiRustBoolObservableObserver {
    fn next(&self, value: bool) {
        ValdiRustBoolObservableObserver::next(self, value);
    }

    fn release(&self) {
        ValdiRustBoolObservableObserver::release(self);
    }
}

impl ValdiRustObserver<i64> for ValdiRustLongObservableObserver {
    fn next(&self, value: i64) {
        ValdiRustLongObservableObserver::next(self, value);
    }

    fn release(&self) {
        ValdiRustLongObservableObserver::release(self);
    }
}

impl ValdiRustObserver<String> for ValdiRustStringObservableObserver {
    fn next(&self, value: String) {
        let bytes = value.as_bytes();
        let view = ValdiRustStringView {
            data: bytes.as_ptr() as *const c_char,
            len: bytes.len(),
        };
        ValdiRustStringObservableObserver::next(self, view);
    }

    fn release(&self) {
        ValdiRustStringObservableObserver::release(self);
    }
}

impl ValdiRustObserver<Bytes> for ValdiRustBytesObservableObserver {
    fn next(&self, value: Bytes) {
        let view = ValdiRustBytesView {
            data: value.as_ptr(),
            len: value.len(),
        };
        ValdiRustBytesObservableObserver::next(self, view);
    }

    fn release(&self) {
        ValdiRustBytesObservableObserver::release(self);
    }
}

impl<T: Send + 'static> ValdiRustObserver<ValdiRustTypedHandle<T>> for ValdiRustHandleObservableObserver {
    fn next(&self, value: ValdiRustTypedHandle<T>) {
        ValdiRustHandleObservableObserver::next(self, value.into_return_handle());
    }

    fn release(&self) {
        ValdiRustHandleObservableObserver::release(self);
    }
}

impl<T: Send + 'static> ValdiRustObserver<ValdiRustRetainedHandle<T>> for ValdiRustHandleObservableObserver {
    fn next(&self, value: ValdiRustRetainedHandle<T>) {
        ValdiRustHandleObservableObserver::next(self, value.as_typed_handle().into_return_handle());
    }

    fn release(&self) {
        ValdiRustHandleObservableObserver::release(self);
    }
}

struct ValdiRustBehaviorSubjectState<T, Observer> {
    value: T,
    observers: Vec<Option<Observer>>,
}

pub struct ValdiRustBehaviorSubject<T, Observer> {
    state: Mutex<ValdiRustBehaviorSubjectState<T, Observer>>,
}

impl<T, Observer> ValdiRustBehaviorSubject<T, Observer>
where
    T: Clone + Send + 'static,
    Observer: ValdiRustObserver<T>,
{
    pub fn new(value: T) -> Self {
        Self {
            state: Mutex::new(ValdiRustBehaviorSubjectState {
                value,
                observers: Vec::new(),
            }),
        }
    }

    pub fn get(&self) -> T {
        self.state
            .lock()
            .expect("ValdiRustBehaviorSubject mutex poisoned")
            .value
            .clone()
    }

    pub fn next(&self, value: T) {
        let observers = {
            let mut state = self
                .state
                .lock()
                .expect("ValdiRustBehaviorSubject mutex poisoned");
            state.value = value.clone();
            state.observers.iter().flatten().copied().collect::<Vec<_>>()
        };

        for observer in observers {
            observer.next(value.clone());
        }
    }

    pub fn subscribe(&'static self, observer: Observer) -> ValdiRustObservableSubscription {
        let (observer_id, value) = {
            let mut state = self
                .state
                .lock()
                .expect("ValdiRustBehaviorSubject mutex poisoned");
            let observer_id = match state.observers.iter().position(Option::is_none) {
                Some(index) => {
                    state.observers[index] = Some(observer);
                    index
                }
                None => {
                    state.observers.push(Some(observer));
                    state.observers.len() - 1
                }
            };
            (observer_id, state.value.clone())
        };

        observer.next(value);

        ValdiRustObservableSubscription::from_state((self, observer_id), unsubscribe_behavior_subject::<T, Observer>)
    }
}

impl<T, Observer> ValdiRustObservable<Observer> for &'static ValdiRustBehaviorSubject<T, Observer>
where
    T: Clone + Send + 'static,
    Observer: ValdiRustObserver<T>,
{
    fn subscribe(self, observer: Observer) -> ValdiRustObservableSubscription {
        ValdiRustBehaviorSubject::subscribe(self, observer)
    }
}

fn unsubscribe_behavior_subject<T, Observer>(
    (subject, observer_id): (&'static ValdiRustBehaviorSubject<T, Observer>, usize),
) where
    T: Clone + Send + 'static,
    Observer: ValdiRustObserver<T>,
{
    let observer = {
        let mut state = subject
            .state
            .lock()
            .expect("ValdiRustBehaviorSubject mutex poisoned");
        state
            .observers
            .get_mut(observer_id)
            .and_then(Option::take)
    };

    if let Some(observer) = observer {
        observer.release();
    }
}

pub type Observable<T> = &'static BehaviorSubject<T>;
pub type BehaviorSubject<T> = ValdiRustBehaviorSubject<T, <T as ValdiRustObservableValue>::Observer>;
pub type CallbackObservable<T> = ValdiRustCallbackObservable<<T as ValdiRustObservableValue>::Observer>;
pub type DoubleObservable = Observable<Double>;
pub type DoubleBehaviorSubject = BehaviorSubject<Double>;
pub type DoubleCallbackObservable = CallbackObservable<Double>;
pub type BoolObservable = Observable<Bool>;
pub type BoolBehaviorSubject = BehaviorSubject<Bool>;
pub type BoolCallbackObservable = CallbackObservable<Bool>;
pub type LongObservable = Observable<Long>;
pub type LongBehaviorSubject = BehaviorSubject<Long>;
pub type LongCallbackObservable = CallbackObservable<Long>;
pub type StringObservable = Observable<String>;
pub type StringBehaviorSubject = BehaviorSubject<String>;
pub type StringCallbackObservable = CallbackObservable<String>;
pub type BytesObservable = Observable<Bytes>;
pub type BytesBehaviorSubject = BehaviorSubject<Bytes>;
pub type BytesCallbackObservable = CallbackObservable<Bytes>;
pub type HandleCallbackObservable = ValdiRustCallbackObservable<ValdiRustHandleObservableObserver>;
"""

def valdi_rust_native_module(
        name,
        rust_srcs,
        crate_root,
        module,
        crate_name = None,
        cxx_srcs = None,
        cxx_hdrs = None,
        rust_deps = None,
        cxx_deps = None,
        edition = "2024",
        alwayslink = True,
        visibility = None,
        target_compatible_with = None,
        **rust_kwargs):
    """Builds a Rust-backed native module implementation for valdi_module(rust_deps = ...).

    The Rust code is compiled as a static library and linked with the generated
    {module}_rust_bridge target. The bridge is emitted by the Valdi compiler from
    the module's @ExportModule TypeScript declaration, so module authors do not
    need to hand-write C++ adapter classes.
    """
    if cxx_srcs == None:
        cxx_srcs = []
    if cxx_hdrs == None:
        cxx_hdrs = []
    if rust_deps == None:
        rust_deps = []
    if cxx_deps == None:
        cxx_deps = []

    module_label = native.package_relative_label(module)
    generated_bridge_dep = module_label.relative(":" + module_label.name + "_rust_bridge")
    generated_bridge_rs_dep = module_label.relative(":rust.rust_bridge.srcs")
    rust_support_name = name + "_rust_support"
    rust_support_file = name + "_valdi_rust_support.rs"
    rust_static_name = name + "_rust_static"
    rust_kwargs = dict(rust_kwargs)
    rustc_env = dict(rust_kwargs.pop("rustc_env", {}))
    compile_data = list(rust_kwargs.pop("compile_data", []))
    data = list(rust_kwargs.pop("data", []))

    if rustc_env.get("VALDI_RUST_SUPPORT_PATH"):
        fail("valdi_rust_native_module reserves VALDI_RUST_SUPPORT_PATH")
    if rustc_env.get("VALDI_RUST_USER_ROOT_PATH"):
        fail("valdi_rust_native_module reserves VALDI_RUST_USER_ROOT_PATH")

    write_file(
        name = rust_support_name,
        out = rust_support_file,
        content = _VALDI_RUST_SUPPORT_RS.split("\n"),
        newline = "unix",
        visibility = ["//visibility:private"],
    )

    rustc_env["VALDI_RUST_SUPPORT_PATH"] = "$(execpath :{})".format(rust_support_name)
    rustc_env["VALDI_RUST_USER_ROOT_PATH"] = "$(execpath {})".format(crate_root)

    rust_static_library(
        name = rust_static_name,
        srcs = rust_srcs + [
            generated_bridge_rs_dep,
            ":" + rust_support_name,
        ],
        crate_name = crate_name or name,
        crate_root = generated_bridge_rs_dep,
        compile_data = compile_data + [":" + rust_support_name],
        data = data + [
            ":" + rust_support_name,
            crate_root,
        ],
        edition = edition,
        rustc_env = rustc_env,
        deps = rust_deps,
        visibility = ["//visibility:private"],
        **rust_kwargs
    )

    cc_kwargs = {
        "name": name,
        "srcs": cxx_srcs,
        "hdrs": cxx_hdrs,
        "deps": cxx_deps + [generated_bridge_dep, ":" + rust_static_name],
        "alwayslink": alwayslink,
    }
    if target_compatible_with != None:
        cc_kwargs["target_compatible_with"] = target_compatible_with
    if visibility != None:
        cc_kwargs["visibility"] = visibility

    native.cc_library(**cc_kwargs)

def _valdi_rust_web_deps_impl(ctx):
    module_name = ctx.attr.module_name
    if not module_name:
        module_name = paths.basename(ctx.label.package)

    inputs = ctx.files.js_loader + ctx.files.wasm + ctx.files.dts + ctx.files.data
    outputs = []
    for src in inputs:
        out = ctx.actions.declare_file(paths.join(module_name, "web", src.basename))
        ctx.actions.run_shell(
            inputs = [src],
            outputs = [out],
            arguments = [src.path, out.path],
            command = "cp \"$1\" \"$2\"",
            mnemonic = "ValdiRustWebDep",
            progress_message = "Packaging Rust/WASM web artifact {}".format(src.basename),
        )
        outputs.append(out)

    return [DefaultInfo(files = depset(outputs))]

valdi_rust_web_deps = rule(
    implementation = _valdi_rust_web_deps_impl,
    attrs = {
        "js_loader": attr.label_list(
            allow_files = [".js"],
            mandatory = True,
            doc = "JavaScript loader module that registers or exports the web polyglot implementation.",
        ),
        "wasm": attr.label_list(
            allow_files = [".wasm"],
            mandatory = True,
            doc = "Rust-generated WebAssembly artifacts loaded by js_loader.",
        ),
        "dts": attr.label_list(
            allow_files = [".d.ts"],
            default = [],
            doc = "Optional declarations for the web native module.",
        ),
        "data": attr.label_list(
            allow_files = True,
            default = [],
            doc = "Additional adjacent runtime files needed by the loader.",
        ),
        "module_name": attr.string(
            default = "",
            doc = "Valdi module name. Defaults to the package basename.",
        ),
    },
    doc = "Packages Rust/WASM web artifacts under <module>/web so Valdi's web native-module collapse and registration rules can consume them.",
)
